<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Deterministic>true</Deterministic>
        <InvariantGlobalization>true</InvariantGlobalization>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>

        <Authors>Jerrett Davis</Authors>
        <RepositoryUrl>https://github.com/JerrettDavis/EspScreenBarcodeGenerator</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>
